# Generated by Django 3.2 on 2021-11-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('name', models.CharField(max_length=50, verbose_name='Board_name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('name', models.CharField(max_length=30, verbose_name='Board_tab')),
                ('board_order', models.IntegerField(verbose_name='Order_of_the_tab')),
                ('is_default', models.BooleanField(blank=True, choices=[(None, 'False'), (True, 'True')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('perm_admin', models.BooleanField(default=False, verbose_name='Admin_permission')),
                ('perm_create', models.BooleanField(default=False, verbose_name='Create_permission')),
                ('perm_read', models.BooleanField(default=False, verbose_name='Read_permission')),
                ('perm_update', models.BooleanField(default=False, verbose_name='Update_permission')),
                ('perm_delete', models.BooleanField(default=False, verbose_name='Delete_permission')),
            ],
        ),
        migrations.CreateModel(
            name='GenericPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('code', models.CharField(max_length=36, unique=True, verbose_name='Password_code')),
                ('signature', models.BinaryField(max_length=40, verbose_name='Password_signature')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('code', models.CharField(max_length=36, unique=True, verbose_name='Password_code')),
                ('signature', models.BinaryField(max_length=40, verbose_name='Password_signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created_by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_owner', to=settings.AUTH_USER_MODEL, verbose_name='Password_owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='BoardPassword',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='board_password', serialize=False, to='main.genericpassword', verbose_name='Generic_password_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_password', serialize=False, to='main.genericpassword', verbose_name='Generic_password_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPasswordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True, verbose_name='Can_read')),
                ('share', models.BooleanField(default=False, verbose_name='Can_share')),
                ('update', models.BooleanField(default=False, verbose_name='Can_update')),
                ('owner', models.BooleanField(default=False, verbose_name='Is_owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('assignment_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpasswordassignment_assignment_owner', to=settings.AUTH_USER_MODEL, verbose_name='Assignment_owner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpasswordassignment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created_by')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.password', verbose_name='Password')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpasswordassignment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddIndex(
            model_name='genericpassword',
            index=models.Index(fields=['title'], name='generic_password_title_idx'),
        ),
        migrations.AddField(
            model_name='boarduserassignment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='main.board', verbose_name='Board'),
        ),
        migrations.AddField(
            model_name='boarduserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='boardtab',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tabs', to='main.board', verbose_name='Board'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Board_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='userpasswordassignment',
            unique_together={('user', 'password')},
        ),
        migrations.AddField(
            model_name='userpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='password',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boarduserassignment',
            unique_together={('board', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='boardtab',
            unique_together={('board', 'is_default'), ('board', 'board_order')},
        ),
        migrations.AddField(
            model_name='boardpassword',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.board', verbose_name='Board'),
        ),
        migrations.AddField(
            model_name='boardpassword',
            name='board_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.boardtab', verbose_name='Board_tab'),
        ),
    ]
