# Generated by Django 3.2 on 2021-05-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models.fields.bit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                # ('code', models.BinaryField(max_length=16, verbose_name='Password_code')),
                # ('signature', models.BinaryField(max_length=40, verbose_name='Password_signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created_by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_owner', to=settings.AUTH_USER_MODEL, verbose_name='Password_owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_name')),
            ],
        ),
        migrations.RunSQL("""
            ALTER TABLE main_password
            ADD code BINARY(16) NOT NULL,
            ADD signature BINARY(40) NOT NULL
        """,
        reverse_sql="""
            ALTER TABLE main_password
            DROP COLUMN code, 
            DROP COLUMN signature
        """),
        migrations.CreateModel(
            name='UserPasswordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', django_mysql.models.fields.bit.Bit1BooleanField(default=True, verbose_name='Can_read')),
                ('share', django_mysql.models.fields.bit.Bit1BooleanField(default=False, verbose_name='Can_share')),
                ('update', django_mysql.models.fields.bit.Bit1BooleanField(default=False, verbose_name='Can_update')),
                ('owner', django_mysql.models.fields.bit.Bit1BooleanField(default=False, verbose_name='Is_owner')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.password', verbose_name='Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'password')},
            },
        ),
        migrations.RunSQL("""
            CREATE INDEX code_idx ON main_password (code(16))
        """,
        reverse_sql="""
            DROP INDEX code_idx ON main_password
        """),
        migrations.RunSQL("""
            CREATE INDEX title_idx ON main_password (title(50))
        """,
        reverse_sql="""
            DROP INDEX title_idx ON main_password
        """),

        # Database integrity validation triggers
        migrations.RunSQL("""
CREATE TRIGGER main_password_tr_upd BEFORE UPDATE ON main_password
FOR EACH ROW
BEGIN
	IF EXISTS (SELECT 1 FROM main_userpasswordassignment WHERE main_userpasswordassignment.user_id = NEW.owner_id) THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Duplicate for assignment to password. Password main owner cannot be assigned to the password again';
	END IF;
END
        """, 
        reverse_sql="""
DROP TRIGGER main_password_tr_upd
        """),
        migrations.RunSQL("""
CREATE TRIGGER main_userpasswordassignment_tr_ins BEFORE INSERT ON main_userpasswordassignment
FOR EACH ROW
BEGIN
	IF EXISTS (SELECT 1 FROM main_password WHERE main_password.owner_id = NEW.user_id) THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Duplicate for assignment to password. Password main owner cannot be assigned to the password again';
	END IF;
END
        """,
        reverse_sql="""
DROP TRIGGER main_userpasswordassignment_tr_ins
        """),
        migrations.RunSQL("""
CREATE TRIGGER main_userpasswordassignment_tr_upd BEFORE UPDATE ON main_userpasswordassignment
FOR EACH ROW
BEGIN
	IF EXISTS (SELECT 1 FROM main_password WHERE main_password.owner_id = NEW.user_id) THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Duplicate for assignment to password. Password main owner cannot be assigned to the password again';
	END IF;
END
        """,
        reverse_sql="""
DROP TRIGGER main_userpasswordassignment_tr_upd
        """)
    ]
