# Generated by Django 3.2 on 2021-11-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardtab',
            unique_together={('board', 'is_default')},
        ),
    ]
