# Generated by Django 3.2 on 2021-06-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswordassignment',
            name='assignment_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpasswordassignment_assignment_owner', to=settings.AUTH_USER_MODEL, verbose_name='Assignment_owner'),
        ),
    ]
