# Generated by Django 3.2 on 2021-12-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_boardtab_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardpassword',
            old_name='id',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='boardpassword',
            name='board_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tab_passwords', to='main.boardtab', verbose_name='Board_tab'),
        ),
    ]
