# Generated by Django 3.2 on 2021-12-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_assign_user_tabs(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserTab = apps.get_model("main", "UserTab")
    db_alias = schema_editor.connection.alias

    users = User.objects.using(db_alias).all()
    user_tabs = []
    for user in users:
        obj = UserTab(
            user=user,
            name="Default tab",
            order=1,
            is_default=True
        )
        user_tabs.append(obj)

    UserTab.objects.using(db_alias).bulk_create(user_tabs)


def reverse_assign_user_tabs(apps, schema_editor):
    # No need to do anything. Reversing the migration will remove UserTabs table from the database
    return

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20211202_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='id',
        ),
        migrations.AddField(
            model_name='userpassword',
            name='password',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_password', serialize=False, to='main.genericpassword', verbose_name='Generic_password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tab_name')),
                ('order', models.IntegerField(verbose_name='Order_of_the_tab')),
                ('is_default', models.BooleanField(blank=True, choices=[(None, 'False'), (True, 'True')], default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tabs', to=settings.AUTH_USER_MODEL, verbose_name='User_tab')),
            ],
            options={
                'unique_together': {('user', 'is_default')},
            },
        ),
        migrations.AddField(
            model_name='userpassword',
            name='user_tab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tab_passwords', to='main.usertab', verbose_name='User_tab'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPasswordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('created_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Updated_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_shares', to='main.userpassword', verbose_name='User_password')),
            ],
            options={
                'unique_together': {('user', 'user_password')},
            },
        ),
        migrations.RunPython(forward_assign_user_tabs, reverse_assign_user_tabs)
    ]
