const STANDARD_ERRORS = {
    UNKNOWN: -1,
    VALIDATION: 0,
    NETWORK_ERROR: 1,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    THROTTLING: 429,
    INTERNAL_SERVER_ERROR: 500
};

export default STANDARD_ERRORS;