version: '3'

services:
    database-passmanager:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password --max_sp_recursion_depth=10 --innodb-use-native-aio=0
        environment:
            - MYSQL_DATABASE=passmanager_dev01
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=Admin123!
            - MYSQL_ROOT_PASSWORD=Admin123!
        volumes:
            - ./database/persistant_storage/:/var/lib/mysql
            - ./database/custom.cnf:/etc/mysql/conf.d/custom.cnf
        ports:
            - 3306:3306
    
    adminer:
        image: adminer:4.7
        ports:
            - 8081:8080