#!/bin/bash
echo "Initializing database..."

# ---------- MYSQL -----------
mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOF

CREATE DATABASE $INIT_DATABASE_NAME;

CREATE USER '$INIT_APPLICATION_USER_USERNAME'@'$INIT_DJANGO_IPV4' IDENTIFIED BY '$INIT_APPLICATION_USER_PASSWORD';
CREATE USER '$INIT_ADMIN_USER_USERNAME'@'$INIT_ADMINER_IPV4' IDENTIFIED BY '$INIT_ADMIN_USER_PASSWORD';

GRANT ALL ON $INIT_DATABASE_NAME.* TO '$INIT_APPLICATION_USER_USERNAME'@'$INIT_DJANGO_IPV4';
GRANT ALL ON $INIT_DATABASE_NAME.* TO '$INIT_ADMIN_USER_USERNAME'@'$INIT_ADMINER_IPV4';

EOF

echo "Database initialized"