version: '3'

services:
    passmanager_db:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password --max_sp_recursion_depth=10 --innodb-use-native-aio=0 --character-set-server=utf8 --collation-server=utf8_polish_ci
        environment:
            - MYSQL_DATABASE=$DATABASE_NAME
            - MYSQL_USER=$DATABASE_USER
            - MYSQL_PASSWORD=$DATABASE_PASSWORD
            - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
        volumes:
            - ./database/persistent_storage/:/var/lib/mysql
        expose:
            - "3006"

    passmanager_web:
        build: ./app
        command: sh -c "pip install -r requirements.txt &&
                        pip install -r prod_requirements.txt &&
                        python manage.py migrate &&
                        gunicorn wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - static_volume:/home/app/web/public/static
            - media_volume:/home/app/web/public/media
            - ./app/protected:/home/app/web/protected
        depends_on:
            - "passmanager_db"
        restart: "on-failure"
        environment:
            - DEBUG=$WEB_DEBUG
            - SECRET_KEY=$WEB_SECRET_KEY
            - ALLOWED_HOSTS=$WEB_ALLOWED_HOSTS
            - CORS_ORIGIN_WHITELIST=$WEB_CORS_ORIGIN_WHITELIST
            - DB_HOST=$DATABASE_HOST
            - DB_NAME=$DATABASE_NAME
            - DB_USER=$DATABASE_USER
            - DB_PASSWORD=$DATABASE_PASSWORD
        expose:
            - "8000"

        working_dir: /home/app/web

    passmanager_npm:
        build: ./npm
        expose:
            - "80"

    nginx:
        build: ./nginx
        ports:
            - 8082:80
            - $WEB_PORT:443
            - $NPM_PORT:444
        depends_on:
            - passmanager_web
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media

    adminer:
        image: adminer:latest
        ports:
            - $ADMINER_PORT:8080

volumes:
    static_volume:
    media_volume: